title: curtistinkers Apt Repository
description: My custom apt repository
theme: jekyll-theme-leap-day
version: 1.0.0

url: "https://apt.curtistinkers.com"
baseurl: ""

exclude:
  - .github/
  - cache/
  - CNAME
  - LICENSE.md
  - README.md
