Dir {
  ArchiveDir ".";
  CacheDir ".";
};

Default {
  Packages::Compress ". gzip";
  Packages::Extensions "deb";
};

BinDirectory "dists/trixie/main/binary-amd64" {
  Packages "dists/trixie/main/binary-amd64/Packages";
};

BinDirectory "dists/trixie/main/binary-all" {
  Packages "dists/trixie/main/binary-all/Packages";
};

BinDirectory "dists/pve9/main/binary-amd64" {
  Packages "dists/pve9/main/binary-amd64/Packages";
};

BinDirectory "dists/pve9/main/binary-all" {
  Packages "dists/pve9/main/binary-all/Packages";
};
