APT::FTPArchive::Release::Origin "curtistinkers APT Repository";
APT::FTPArchive::Release::Label "Packages host by curtistinkers";
APT::FTPArchive::Release::Suite "pve8";
APT::FTPArchive::Release::Codename "pve8";
APT::FTPArchive::Release::Architectures "amd64 all source";
APT::FTPArchive::Release::Components "main non-free"; # MUST match Sections
APT::FTPArchive::Release::Description "Universal configuration and specialized tools for Proxmox VE 8.";
