APT::FTPArchive::Release::Codename "pve9";
APT::FTPArchive::Release::Origin "curtistinkers APT Repository";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Label "Packages host by curtistinkers";
APT::FTPArchive::Release::Architectures "amd64 all source";
APT::FTPArchive::Release::Suite "pve9";
APT::FTPArchive::Release::Description "Universal configuration and specialized tools for Proxmox VE 9.";
