APT::FTPArchive::Release::Origin "curtistinkers APT Repository";
APT::FTPArchive::Release::Label "curtistinkers";
APT::FTPArchive::Release::Suite "pve9";
APT::FTPArchive::Release::Codename "pve9";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Combined universal configuration and specialized tools for Proxmox VE 9 hypervisors.";
