APT::FTPArchive::Release::Origin "curtistinkers APT Repository";
APT::FTPArchive::Release::Label "curtistinkers";
APT::FTPArchive::Release::Suite "trixie";
APT::FTPArchive::Release::Codename "trixie";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Universal configuration packages for Debian Trixie nodes.";
